// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOTTracker.Data;

#nullable disable

namespace OOTTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240518095948_AddCollectables")]
    partial class AddCollectables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OOTTracker.Data.Collectable", b =>
                {
                    b.Property<Guid>("CollectableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectableTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CollectableId");

                    b.HasIndex("CollectableTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Collectables");
                });

            modelBuilder.Entity("OOTTracker.Data.CollectableType", b =>
                {
                    b.Property<Guid>("CollectableTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollectableTypeId");

                    b.ToTable("CollectableTypes");
                });

            modelBuilder.Entity("OOTTracker.Data.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("OOTTracker.Data.Collectable", b =>
                {
                    b.HasOne("OOTTracker.Data.CollectableType", "CollectableType")
                        .WithMany("Collectables")
                        .HasForeignKey("CollectableTypeId");

                    b.HasOne("OOTTracker.Data.Location", "Location")
                        .WithMany("Collectables")
                        .HasForeignKey("LocationId");

                    b.Navigation("CollectableType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OOTTracker.Data.CollectableType", b =>
                {
                    b.Navigation("Collectables");
                });

            modelBuilder.Entity("OOTTracker.Data.Location", b =>
                {
                    b.Navigation("Collectables");
                });
#pragma warning restore 612, 618
        }
    }
}
